console.log("Rodando o sistema de gerenciamnento de jogos")
console.log("Programa rodando")
console.log("Programa rodando")
console.log("Programa rodando")
console.log("Programa rodando")
console.log("Programa rodando")
console.log("Programa rodando")
console.log("Programa rodando")
console.log("Programa rodando")
